// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2d9xx3EvuvZJEECdaaNYcMhVw8vimzGg',
    appId: '1:653581282474:web:3c33eac3a962eafa1534d3',
    messagingSenderId: '653581282474',
    projectId: 'dingmo-76ec3',
    authDomain: 'dingmo-76ec3.firebaseapp.com',
    storageBucket: 'dingmo-76ec3.appspot.com',
    measurementId: 'G-MZFKVGFLZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYC43mCd0ag4nc2rFaaQ-lO_gbaFsTPtM',
    appId: '1:653581282474:android:e4911a663c7a63211534d3',
    messagingSenderId: '653581282474',
    projectId: 'dingmo-76ec3',
    storageBucket: 'dingmo-76ec3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-BKYmhc5f8P0syhDLach1JTKz8XFMsM',
    appId: '1:653581282474:ios:c6daea5b2ac8eb951534d3',
    messagingSenderId: '653581282474',
    projectId: 'dingmo-76ec3',
    storageBucket: 'dingmo-76ec3.appspot.com',
    iosClientId: '653581282474-gj0sgq3dl3jesjp0195roeqflj0ra0t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dingmo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-BKYmhc5f8P0syhDLach1JTKz8XFMsM',
    appId: '1:653581282474:ios:c6daea5b2ac8eb951534d3',
    messagingSenderId: '653581282474',
    projectId: 'dingmo-76ec3',
    storageBucket: 'dingmo-76ec3.appspot.com',
    iosClientId: '653581282474-gj0sgq3dl3jesjp0195roeqflj0ra0t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dingmo',
  );
}
