/// Flutter icons Dingmo
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dingmo
///      fonts:
///       - asset: fonts/Dingmo.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Dingmo {
  Dingmo._();

  static const _kFontFam = 'Dingmo';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData smile_icon =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData shots_icon =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData home_icon =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
